#!/bin/bash

cd stage2_2808
./compile > ../cresult
cd ..

cp unlock_up.asm unlock.asm

cat ./cresult | grep 3f8 | gawk '{i=substr($0,0,6)} {printf("xtest:\t\tlb\t#0x%s\n",i)}' >jump_to_c.asm


tms2000_asm boot_stage1
./makeboot.pl boot_stage1.lst unlock_up.asm

./create_loader
