#!/bin/bash

/home/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000 -v28 -ml -I/usr/local/include/c2000 main.c \
DSP280x_GlobalVariableDefs.c \
DSP280x_Gpio.c \
DSP280x_SysCtrl.c \
codestart.asm

/home/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/cl2000 -v28 -z --ram_model -o result.out main.obj \
DSP280x_GlobalVariableDefs.obj \
DSP280x_Gpio.obj \
DSP280x_SysCtrl.obj \
codestart.obj \
--library=/usr/local/lib/c2000/rts2800_ml.lib \
--library=Flash280x/Flash2808_API_V302.lib \
--diag_suppress=16002 \
-ml scripts/link_ram.cmd scripts/DSP280x_Headers_nonBIOS.cmd

/home/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/hex2000 scripts/makehex.cmd
/home/ti/ccsv5/tools/compiler/c2000_6.1.3/bin/dis2000 result.out > result.asm

mv result.lsb ../
mv result.msb ../

rm -f *.obj
rm -f *.out

cat result.asm | grep "int00:"